### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by GCB2023** [masoudgb/Xtream-Ui#4]
Installing Software               │
 └─────────────────────────────────────────────────┘

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
 ┌─────────────────────────────────────────────────┐
 │               Configuring MySQL                 │
 └─────────────────────────────────────────────────┘

sh: 1: cannot open /home/xtreamcodes/iptv_xtream_codes/database.sql: No such file
ERROR 1146 (42S02) at line 1: Table 'xtream_iptvpro.settings' doesn't exist
ERROR 1146 (42S02) at line 1: Table 'xtream_iptvpro.streaming_servers' doesn't exist
ERROR 1146 (42S02) at line 1: Table 'xtream_iptvpro.reg_users' doesn't exist
 ┌─────────────────────────────────────────────────┐
 │                 Encrypting...                   │
 └─────────────────────────────────────────────────┘

Traceback (most recent call last):
  File "install.py", line 284, in <module>
    encrypt(rHost, rUsername, rPassword, rDatabase, rServerID, rPort)
  File "install.py", line 192, in encrypt
    rf = open('/home/xtreamcodes/iptv_xtream_codes/config', 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/xtreamcodes/iptv_xtream_codes/config'

**Comment by masoudgb** [comment]
> Installing Software │ └─────────────────────────────────────────────────┘
> 
> gzip: stdin: not in gzip format tar: Child returned status 1 tar: Error is not recoverable: exiting now ┌─────────────────────────────────────────────────┐ │ Configuring MySQL │ └─────────────────────────────────────────────────┘
> 
> sh: 1: cannot open /home/xtreamcodes/iptv_xtream_codes/database.sql: No such file ERROR 1146 (42S02) at line 1: Table 'xtream_iptvpro.settings' doesn't exist ERROR 1146 (42S02) at line 1: Table 'xtream_iptvpro.streaming_servers' doesn't exist ERROR 1146 (42S02) at line 1: Table 'xtream_iptvpro.reg_users' doesn't exist ┌─────────────────────────────────────────────────┐ │ Encrypting... │ └─────────────────────────────────────────────────┘
> 
> Traceback (most recent call last): File "install.py", line 284, in encrypt(rHost, rUsername, rPassword, rDatabase, rServerID, rPort) File "install.py", line 192, in encrypt rf = open('/home/xtreamcodes/iptv_xtream_codes/config', 'wb') FileNotFoundError: [Errno 2] No such file or directory: '/home/xtreamcodes/iptv_xtream_codes/config'

Please write the operating system version and server architecture

**Comment by GCB2023** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble
x86_64 AMD
and we try download the main_xui_masoudgb.tar.gz and 
use this command “ tar -zxvf main_xui_masoudgb.tar.gz -C /home/xtreamcodes/”
get this error message
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

same error.

**Comment by GCB2023** [comment]
already install
use tar -xvf main_xui_masoudgb.tar.gz -C /home/xtreamcodes/
can unzip it.

**Comment by masoudgb** [comment]
> Distributor ID: Ubuntu Description: Ubuntu 24.04 LTS Release: 24.04 Codename: noble x86_64 AMD and we try download the main_xui_masoudgb.tar.gz and use this command “ tar -zxvf main_xui_masoudgb.tar.gz -C /home/xtreamcodes/” get this error message gzip: stdin: not in gzip format tar: Child returned status 1 tar: Error is not recoverable: exiting now
> 
> same error.

The problem was fixed in the new update.
